### ISSUE TITLE
[Question] Does Kafka consumer retry indefinitely?

### ISSUE THREAD

**Issue by quynhethereal** [karafka/karafka#1028]
Hi! First of all, thank you for the awesome project ❤️ 

It is mentioned in the docs that ([After that time, it will retry, processing the same message again. Single Kafka topic partition messages must be processed in order.](https://github.com/karafka/karafka/wiki/Error-handling-and-back-off-policy#:~:text=partition%2C%20back%20off%2C-,and,-wait%20for%20a)). 

My questions/understandings that need confirming are as below:
- From this, I understand that **the consumer would retry the message indefinitely until the error is no longer raised (i.e the message has been successfully processed) right?** 
- If these lines are set: 
https://github.com/karafka/karafka/blob/3fcce7390b6a7cdd3307d4f9d703f90966a5e790/lib/karafka/setup/config.rb#L86-L88
it would back off exponentially, until reaching the `pause_max_timeout`, then it would continue retry with the `pause_max_timeout` value. 
- If these lines aren't set, the pause period would resort to the `pause_timeout` -> the retry indefinitely behavior still exists in this case. 
- If my observations are correct, if we want to implement a more advanced error handling mechanism such as `Retryable` topic (so that the consumer does not block the topic from consuming the failed message over and over again), we would have to do it ourselves as Karafka does not support it natively. 

Thank you in advance!

**Comment by mensfeld** [comment]
You understand this correctly, however there is a hope!

I already started working on https://github.com/karafka/karafka/issues/956

This will include full DLQ with proper policies configuration and proper proxying of failed messages with both per message and batch strategies.

You can ofc implement it yourself instead of waiting. Karafka keeps track of errors in the pause object: 

https://github.com/karafka/karafka/blob/3fcce7390b6a7cdd3307d4f9d703f90966a5e790/lib/karafka/time_trackers/pause.rb#L7

You can access it from the consumer via coordinator:

https://github.com/karafka/karafka/blob/3fcce7390b6a7cdd3307d4f9d703f90966a5e790/lib/karafka/processing/coordinator.rb#L14

to get the number of retries that occurred.

**Comment by quynhethereal** [comment]
Wow, this is so promising!! I'm really excited about the update 😄 Fingers crossed, and thank you again for your great, hard work 💯

**Comment by mensfeld** [comment]
Thank you for your appreciation.

You will have to wait few more weeks as despite it "looking simple" there are many edge cases that need to be covered. On top of that I need to make sure that DLQ works as expected with other Karafka features.
