### ISSUE TITLE
Exponential backoff raised two times more errors

### ISSUE THREAD

**Issue by NotGrm** [karafka/karafka#1114]
As discussed on Slack, I have enabled exponential backoff pause to limit the number of error that was reported to our bug tracker in order to let us fix the issue.

Here what I have added to `karafka.rb` file

```ruby
class KarafkaApp < Karafka::App
  setup do |config|
    # other config have not changed

    # Double time between invalid consumes so that it limit number of reported
    # errors to let us fix them
    config.pause_max_timeout = 10_800 # 3 hours
    config.pause_with_exponential_backoff = true
  end
end
```

But since I deployed that change, I see that the number of error reported has double, as if Karafka is polling more often than before messages 

![Capture d’écran 2022-11-04 à 15 44 32](https://user-images.githubusercontent.com/793603/200003423-a1242e4a-37d3-4da9-94d3-61cdc3d67d84.png)

## Your setup details

```
$ [bundle exec] karafka info
Karafka version: 2.0.15
Ruby version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-darwin21]
Rdkafka version: 0.12.0
Subscription groups count: 1
Workers count: 5
Environment: development
License: LGPL-3.0
```

**Comment by NotGrm** [comment]
Closing the issue for now, because disabling exponential backoff pause has not reduced the number of reported errors. So it may be an external factor that explain that.

**Comment by vestedpr-dev** [comment]
It has been some time but, the reason behind this issue is just that the `pause_max_timeout` is specified in milliseconds, and the default is 30,000 milliseconds. So setting it to 10,800 milliseconds inadvertently caused the number of exception to roughly triple. To set it to three hours for real, the number would be:  3 hours * 3600 seconds / hour * 1000 ms / sec = 10,800,000.

**Comment by vestedpr-dev** [comment]
Your gem is amazing & handles an amazingly sophisticated/ complex situation
well.

Sentences like this in the docs
https://karafka.io/docs/Error-handling-and-back-off-policy/#finding-the-failing-message
"If pause_with_exponential_backoff is enabled, each subsequent pause will
cause the timeout to double until a message from the partition has been
successfully processed. To not double the time indefinitely, you can please
set pause_max_timeout to whatever you consider max pause." -- this is a bit
misaligned with the defaults: pause_with_exponential_backoff is enabled by
default, and pause_max_timeout is set to 30s by default. You might want to
look at these phrases in the light of the default values, as that will be
most folks' first encounter with the feature.

FAQ: "If pause_with_exponential_backoff is enabled, why am I still seeing
hundreds of repeat exceptions when something breaks?" pause_max_timeout is
set to 30 seconds by default, so your exception will still occur 120 times
per hour until you fix it.

My principal concern in the beginning is not to flood my tiny experimental
exception management system with exceptions, so I increased
pause_max_timeout to be 6 hours instead of 30s.

**Comment by mensfeld** [comment]
Ok. So it's about docs and not the code misbehaving. Great! I'll update what caused the confusion. Sorry for that.

**Comment by mensfeld** [comment]
Updated. Thanks!
