### ISSUE TITLE
Allow both Virtual Partitions and DLQ

### ISSUE THREAD

**Issue by Azdaroth** [karafka/karafka#1229]
## Describe the solution you'd like

Allow both Virtual Partitions and DLQ

## Additional context

A Slack discussion: https://karafka-io.slack.com/archives/C027C6M2B0U/p1671438510282749

**Comment by mensfeld** [comment]
Note on how we could do this while maintaining Kafka warranties:
- when any error happens, we restart all the processing from the "native" batch
- the distribution is now reduced and no virtual partitioning occurs
- we do not virtual partition until we no longer have to DLQ/retry (`coordinator.pause_tracker.attempt.zero?`)
- once we're back on track we continue using VPs.

This will effectively allow for support of DLQ with VPs while preserving ordering warranties of Kafka and not causing extensive over-engineering.

One thing worth noting: in this combination `max_retries` cannot be set to `0` because we need to be able to run again without VPs distribution.

**Comment by mensfeld** [comment]
Retargeting to 2.0 because of high demand

**Comment by mensfeld** [comment]
This has been done.
