### ISSUE TITLE
RebalanceCallback patch port back to rdkafka-ruby

### ISSUE THREAD

**Issue by jychen7** [karafka/karafka#1510]
## Is your feature request related to a problem? Please describe.

I read through the RebalanceCallback patch and find it reasonable to commit offsets (if any) upon partition revocation.
https://github.com/karafka/karafka/blob/649e323536d5319b99c699948ca0f9ac214d1490/lib/karafka/patches/rdkafka/bindings.rb#L70-L72
https://github.com/karafka/karafka/blob/649e323536d5319b99c699948ca0f9ac214d1490/lib/karafka/patches/rdkafka/bindings.rb#L23-L25
https://github.com/karafka/karafka/blob/649e323536d5319b99c699948ca0f9ac214d1490/lib/karafka/patches/rdkafka/bindings.rb#L40-L42
Is it a plan to port this back to https://github.com/appsignal/rdkafka-ruby?

I understand you are maintainer in rdkafka-ruby as well and you may already think about it. So would love learn more about your thoughts.

**Comment by mensfeld** [comment]
Thank you for taking an interest in Karafka and reading through my codebase. I hope you find it enjoyable. 

To answer your question: I do **not**. It would create a difference between how librdkafka and rdkafka-ruby operate. I **do** however plan to bring instance based rebalance callbacks per consumer instance into rdkafka effectively retiring this patch and providing the ability for anyone else to create any type of behaviour per instance on RB.

librdkafka can be used without offset storage using custom storage instead of kafka. An automatic commit would basically disallow that. Karafka allows you to provide complementary storage (see https://mensfeld.pl/2023/06/inside-kafka-enhancing-data-reliability-through-transactional-offsets-with-karafka/) but makes an assumption that you are using kafka for primary offset management source.

**Comment by mensfeld** [comment]
FYI if you want this and other features faster in librdkafka or want to see the karafka ecosystem grow, please consider supporting my efforts :pray:

**Comment by mensfeld** [comment]
I expanded my initial thoughts here: https://karafka.io/docs/FAQ/#why-karafka-commits-offsets-on-rebalances-and-librdafka-does-not

**Comment by jychen7** [comment]
> Thank you for taking an interest in Karafka and reading through my codebase. I hope you find it enjoyable.

yes, the code is modular and enjoyable to read.

> I do however plan to bring instance based rebalance callbacks per consumer instance into rdkafka effectively
> FYI if you want this and other features faster in librdkafka or want to see the karafka ecosystem grow, please consider supporting my efforts

sure, this callback sounds reasonable. Is there already a github issue tracking this? I could help upvote!

---

> It would create a difference between how librdkafka and rdkafka-ruby operate.
> librdkafka can be used without offset storage using custom storage instead of kafka
> I expanded my initial thoughts here: https://karafka.io/docs/FAQ/#why-karafka-commits-offsets-on-rebalances-and-librdafka-does-not

Thanks for the detailed thought. I was reading [following code in librdkafka](https://github.com/confluentinc/librdkafka/blob/961946e55fb3f89eb782d4011af4bf5cd3c31f17/src-cpp/rdkafkacpp.h#L1008C66-L1014) and thought the reverse case "if auto.commit.enable is true, application doesn't need to commit offsets manually and it is auto committed". Turn out **my understanding is wrong**, so I agree `rdkafka-ruby` should align with `librdkafka` and not commit even `auto.commit.enable=true`

```
   *         } else if (err == RdKafka::ERR__REVOKE_PARTITIONS) {
   *           // Application may commit offsets manually here
   *           // if auto.commit.enable=false
   *           if (consumer->rebalance_protocol() == "COOPERATIVE")
   *             consumer->incremental_unassign(partitions);
   *           else
   *             consumer->unassign();
   *
   *         }
```

**Comment by mensfeld** [comment]
>  Is there already a github issue tracking this? I could help upvote!

https://github.com/appsignal/rdkafka-ruby/issues/82
