### ISSUE TITLE
Configure consumer #producer with the same kafka options

### ISSUE THREAD

**Issue by podruh** [karafka/karafka#1600]
## Is your feature request related to a problem? Please describe.

When using `kafka` routing option to redefine connection to kafka cluster, I expected the same kafka config in provided `producer` for given consumer. Instead default Karafka::App.consumer is returned

This behaviour is not described in documentation and could lead to production-level incidents.

## Describe the solution you'd like

1. Improved documentation in [Configuration](https://karafka.io/docs/Configuration/)
2. Provide `producer` configured for the consumer instance

Any of these solutions are ok by me.

## Describe alternatives you've considered

The alternative is to persist another WaterDrop::Producer, which is easy to setup.

## Additional context

This also breaks the expectation, that messages dispatched to DLQ will be pushed according to topics kafka config:

```ruby
class KarafkaApp < Karafka::App
  setup do |config|
    config.kafka = {'bootstrap.servers': 'cluster-1.local:9092'}
  end

  routes.draw do
    consumer_group 'consumer_group' do
      topic 'topic1' do
        consumer MyConsumer
        kafka({ 'bootstrap.servers': 'cluster-2.local:9092' })
        dead_letter_queue(
          topic: 'topic1.dlq'
        )
      end
    end
  end
end
```
The messages will be dispached to cluster-1, not cluster-2

**Comment by mensfeld** [comment]
Yeah I see how that can be confusing. At the moment producer is not context aware and the docs should be clear about that.

It may also be an interesting addition to the features suite as would easily bound this on a per subscription group setting level.

Both will be addressed though feature wise it is not a priority for me.

**Comment by podruh** [comment]
Honestly the documentation should be enough for now. Karafka is amazing as it is and if I want to use multiple clusters, I should expect some difficulties.

Are you interested in PR by any chance? As I need to solve this anyway, I could try to do it in-gem.

**Comment by mensfeld** [comment]
> Honestly the documentation should be enough for now

Agreed :)

> Karafka is amazing as it is

Thank you for kind words. If your business decides to rely on Karafka, please consider supporting my efforts as well :pray: 

>  if I want to use multiple clusters, I should expect some difficulties.

Here I think we disagree :)

I think Karafka should support this case consistently. The only thing is, we need a producer per subscription group to make sure the settings setup is reflected as expected. This means multiple producers which I anyhow need to have for transactions support, HOWEVER this creates performance problems as it is now because rdkafka-ruby is not using a fiber scheduler for producer statuses polling but separate threads. I have plans to fix that but that's a huge engineering effort, so likely Q1 2024 or later.

**Comment by mensfeld** [comment]
>  Are you interested in PR by any chance? As I need to solve this anyway, I could try to do it in-gem.

Sorry missed that one.

As stated above, you may solve it for your particular case, and it is going to work, however, Karafka deals with people operating on several clusters at the same time and there are heavy engineering challenges that need to be tackled in a few components to back this up efficiently. While I appreciate the effort, this project is huge, mostly because it starts from rdkafka-ruby and replacement of the thread based engine for polling with fiber scheduler, then its propagation to core, waterdrop and then to karafka. Only then we can use the subscription group setting differentiation hash for starting multiple producers in an efficient and scalable way. On top of that Web UI instrumentation needs to automatically connect to newly created producers. I would appreciate help once I'm done with auto-fibers for async polling in rdkafka-ruby.

**Comment by mensfeld** [comment]
If you need to solve this happy to give you some hints for your custom case. Feel free to join us at https://slack.karafka.io/

**Comment by mensfeld** [comment]
FAQ updated: https://karafka.io/docs/FAQ/#can-i-consume-from-more-than-one-kafka-cluster-simultaneously
Producing updated: https://karafka.io/docs/Producing-messages/#producing-to-multiple-clusters
DLQ reference: https://karafka.io/docs/Dead-Letter-Queue/#using-dead-letter-queue-with-a-multi-cluster-setup
