### ISSUE TITLE
Ability to bind multiple controllers to the same topic

### ISSUE THREAD

**Issue by bemurphy** [karafka/karafka#161]
I'm experimenting with Karafka for some potential flows at work. One thing I discovered quickly was I wished I had the ability to subscribe multiple controllers on the same topic.

I tend to notice a proliferation of responsibilities in areas involving user signup as well as ecommerce checkout flows over time. For example, on many SaaS apps I've worked on, we've picked up responsibilities which accrue slowly over time especially around customer acquisition, something like this:

1. Send welcome email to the customer
2. Send an email to the billing team
3. Send an email to the growth/marketing team
4. Add the customer into an onboarding marketing email sequence
5. Add the customer into tracking systems (Intercom, hubspot, etc)
6. Fire analytics events (Hubspot, Intercom, Segment, etc)
7. Send emails to affiliates/partners about sourced signups

You get the drift here.  I'd really like to be able to use a flow in Karafka to extend behavior by creating new controllers and subscribing them to relevant events, rather than opening the existing controllers and adding more code there.

One way to do this as-is would be to make controllers that use something like [wisper](https://github.com/krisleech/wisper) to broadcast an event, and get the pub/sub style behavior that way. But this feels like it's sidestepping the point of having karafka handle that for you.

This is more input for discussion than anything, hopefully it proves to be some useful feedback. I'm not expecting you to "do anything for me" or lodging this as a complaint.

**Comment by mensfeld** [comment]
Hey @bemurphy, thank you for taking interest in Karafka framework. You've added us so many ideas!

I will answer them 1 by 1:

> I'm experimenting with Karafka for some potential flows at work.

Good! :cake: 

>  One thing I discovered quickly was I wished I had the ability to subscribe multiple controllers on the same topic.

That is a great idea!

> You get the drift here. I'd really like to be able to use a flow in Karafka to extend behavior by creating new controllers and subscribing them to relevant events, rather than opening the existing controllers and adding more code there.

*topics - subscribing them to topics. They might consist events but in general they are topics. Karafka is being used also for non event-sourcing based systems (or event based) so it is good to have the same terminology :) (despite the fact that even I mix them quite often :()

> One way to do this as-is would be to make controllers that use something like wisper

Nope. Bad idea. We would end up (in your case) with an event system to which you subscribe, just to subscribe more inside of the process to listen to those events. Sounds a bit complicated.

> I'm not expecting you to "do anything for me" or lodging this as a complaint.

No worries. We totally do things for other. This is open source :dancer: 

Let me point out some problems related to this solution, that we need to solve before implementing that feature (but I'm 100% sure that we will make it):

- As you know, Karafka can be used both in the inline mode (which is being rewritten now as a sync adapter) and with Sidekiq (which is being rewritten as SidekiqAdapter :D), this creates a small issue: how should we handle multiple controllers flow for a single message  from a topic? There are two options (for sync - processing and async - scheduling):
  - 1 by 1 (FIFO)
  - same time (threads? - in ruby 3.0 we will use guilds for that)

  Personally I would be in favour of 1 after another. We would just have an array of controllers that would handle stuff for a given message.
- We need to consider #147  and #126 when doing that
- Routing style is the next concern. @bemurphy would you have any ideas on how the routing DSL could work? Keep in mind that, there are multiple options available for each route that can (optionally) be specified and that otherwise fall-back to default settings for the app itself.

**Comment by bemurphy** [comment]
> *topics - subscribing them to topics. 

Ah, yeah, good to keep the terminology straight. It's possible too that my slipping into saying "events" at times represents the disconnect with the purpose; perhaps I am thinking of it too much like say, event sourcing, or pub/sub with something like RabbitMQ.

> Nope. Bad idea. We would end up (in your case) with an event system to which you subscribe, just to subscribe more inside of the process to listen to those events. Sounds a bit complicated.

Agreed for sure.  Feels like it would be missing the point of the system.

> - 1 by 1 (FIFO)
> - same time (threads? - in ruby 3.0 we will use guilds for that)

FIFO top-down parsing of the file considered FIFO wouldn't surprise me too much.  I'm probably a bit biased because if I was to roll this out in production I would anticipate using sidekiq as much as possible, so the route handling should be  really fast as it's mostly kicking off jobs and not doing heavy lifting.

> Routing style is the next concern. @bemurphy would you have any ideas on how the routing DSL could work?

Yeah, that's a toughie.  Two possibilities I can think of off the top of my head.  First is to not change the DSL, but change the parsing.  So if you hit the `:new_videos` topic for the first time, you push it on to an array.  The second time, push it on, with some additional logic checking that if there are multiples, things are specific enough (meaning you don't automatically bind to the conventional controller twice). A downside to this is, without sometime of either global config flag, or per declaration config flag like `multiple: true`, somebody might not want this behavior and create (or have on upgrade) a config that surprises them.

Another possibility, maybe allow the controller declarations to push on to the stack, or accept a block, and then other DSL methods (like `worker`, etc), could be in that scope?  Put into code, maybe something like this:

```
topic :new_videos do
  controller Videos::NewVideosController do
    worker Videos::DifferentWorker
  end
end
```

I'm trying to think of how Rails routes could positively influence this. I keep thinking of `namespace`, but `topic` here is already being used kind of like that.  Perhaps there's something else I'm not thinking of.

**Comment by mensfeld** [comment]
@bemurphy the more I think about that, the more problems it creates. For example what about sending instances of params and parsing them? with multiple controllers I would imagine that we would have to copy the input message that comes from Kafka, right? But once we get it, the parsing is delayed for delayed processing up until it hits Sidekiq (not in Karafka server runtime). With a copy we would have to do it multiuple times.

**Comment by mensfeld** [comment]
I'm closing this due to the reasons stated above. We will introduce batch message processing soon and binding multiple controllers seems like a huge complication in the context of this feature.
