### ISSUE TITLE
[Question] Consumer class concurrency

### ISSUE THREAD

**Issue by sarvesh-sankaranarayanan** [karafka/karafka#1904]
I have the below configuration
```ruby
routes.draw do
    topic :'topic-a' do
      consumer OneConsumer
    end

    topic :'topic-b' do
      consumer TwoConsumer
    end
end
```

I'm using karafka's default concurrency configuration.
```
Karafka version: 2.3.1
Ruby version: ruby 3.2.0 (2022-12-25 revision a528908271) [x86_64-darwin22]
Rdkafka version: 0.14.10
Consumer groups count: 1
Subscription groups count: 1
Workers count: 5
Application client id: karafka
Boot file: /Users/sasankaranarayanan/test-app/karafka.rb
Environment: development
```

My understanding from the docs is that each consumer class for a topic will have a dedicated thread running for consuming messages from the topic.

Question: Would a consumer class object be shared by multiple threads? Can you tell how the concurrency works for each of the consumer classes.

**Comment by mensfeld** [comment]
> My understanding from the docs is that each consumer class for a topic will have a dedicated thread running for consuming messages from the topic.

No. Docs say:

> After messages are fetched from Kafka, Karafka will split incoming messages into separate jobs. Those jobs will then be put on a queue from which a poll of workers can consume. All the ordering warranties will be preserved.

ref https://karafka.io/docs/Concurrency-and-Multithreading/

There are few flaws in your reasoning:

1. The basic parallelization unit is partition assignment (putting aside virtual partitions for now) and not topics.
2. Same consumer class can be utilized to consume multiple topics partitions but instance of a consumer is always assigned to a currently subscribed and assigned topic partition
3. Consumers classes have nothing to do with any parallelism as assignments build instances of consumers
4. Consumer class (not instance) is always shared between threads because this is how Ruby works
5. Consumers instances are **never** shared across threads but this does **not** mean a single consumer instance is bound to a thread. There is a pool of threads from which karafka picks one and alongside picks appropriate consumer **instance**, binds them together for executions and executes code. This is why you cannot use `Thread.current` for any type of storage assignment and this is why Karafka consumer instances are long lived (amongst other reasons)
