### ISSUE TITLE
Backport #1767 to karafka v2.3 for supporting applications running on ruby <3.0

### ISSUE THREAD

**Issue by jjatinggoyal** [karafka/karafka#2073]
## Is your feature request related to a problem? Please describe.

First of all, thanks for introducing custom OAuth providers with #1767 in karafka v2.4. However, karafka v2.4 has dropped support for ruby versions <3.0. I feel #1767 will be of great use for applications running on older ruby versions as well.

## Describe the solution you'd like

Backport #1767 to karafka v2.3 which has support of ruby v2.7 and earlier.

**Comment by mensfeld** [comment]
No.

Backports happen only for:

- Critical stability (not performance) errors
- Security errors

Pro and Enterprise users can request backports (ref: https://karafka.io/docs/Pro-Support/) however:

> We understand that certain features or fixes can significantly enhance the functionality and stability of your current projects. As a Karafka Pro user, you can request a backport of a particular feature or fix to support your specific needs. Please note that the possibility of backporting will be assessed on a case-by-case basis, taking into account factors like the feasibility of the backport and its impact on system stability.

In this case such request would be rejected. Especially since there are other ways to work with AWS MSK. Karafka dropped 2.7 while Ruby core team itself **already** dropped 3.0 week ago.
