### ISSUE TITLE
params_batch vs ParserError

### ISSUE THREAD

**Issue by RadoslawT** [karafka/karafka#245]
Invoking `map` or `each` method on `params_batch` which includes wrong formatted message, is raising `ParseError` on that message and prevents the rest of the batch's messages to be accessed. I'm not sure if I should write my own parser (according to wiki/Parsers) that won't raise `ParserError` or maybe somehow access unparsed messages and parse them one by one on my own to rescue `ParseError` for the wrong ones.

**Comment by mensfeld** [comment]
Hello Radosław. It really depends on the way you treat malformed data. We assume that unparsable message is an invalid one but I can imagine a different scenarios.

To be honest up until 0.5 we supported unparsable data with the default parser but it was hiding problems for the majority of users expecting always parsable data. 

If I were you, I would write a custom parser and somehow mark the corrupted data, so a different logic can be applied. I would advise against moving that logic (although it can be done) into controllers or corrupting your business with it. Custom parsers were designed exactly for such cases (especially that I can imagine a case in which you're not able to fix corrupted data). 

If this answer satisfies your question, please close the issue. Otherwise feel free to ask more :)

**Comment by RadoslawT** [comment]
Thanks for the fast response! I'll definitely go with the Parser solution.

**Comment by mensfeld** [comment]
@RadoslawT  good luck. Also, don't forget about our gitter channel where you can ask questions and get answers in real time ;)
