### ISSUE TITLE
Racecar breaks Rails loading including Karafka

### ISSUE THREAD

**Issue by ariieh** [karafka/karafka#295]
A recent installation of Karafka broke our Racecar processes on our Rails 5.1.4 app. Here's our setup. `Procfile`:

```
racecar: bundle exec racecar Consumer
karafka: bundle exec karafka server
```

Our `karafka.rb`, just as specified in the documentation:
```ruby
ENV["RAILS_ENV"] ||= "development"
ENV["KARAFKA_ENV"] = ENV["RAILS_ENV"]

require ::File.expand_path("../config/environment", __FILE__)
Rails.application.eager_load!
```

Gemfile:
```ruby
gem "karafka", "1.2.0.beta4"
gem "racecar"
```

And the error we get when trying to run Racecar processes:
```ruby
Gem Load Error is: undefined method `eager_load!' for nil:NilClass
Backtrace for gem load error is:
/app/karafka.rb:7:in `<main>'
```

Which ultimately comes from Racecar requiring gems in `config/application.rb`:
```
Bundler.require(:default, Rails.env)
```
It seems like there's a conflict here between the ways Karafka and Racecar are getting required. Racecar as I understand requires the Rails app, though perhaps not properly?

**Comment by mensfeld** [comment]
Ok, was able to reproduce :)

**Comment by mensfeld** [comment]
In a big shortcut: this is why I don't like gems that integrate with Rails automatically.

Racecar under the hood detects that you want rails by... trying to load rails and if it is able to, will run the whole app before other things are loaded. In most cases this won't cause any trouble but from time to time... well it does.

That's why Karafka does that explicitly in the ```karafka.rb``` file.

To get things going (without the semi loaded rails app) just place the return statement in the karafka.rb like that:

```ruby
# frozen_string_literal: true

# Ruby on Rails setup
# Remove whole non-Rails setup that is above and uncomment the 4 lines below
ENV['RAILS_ENV'] ||= 'development'
ENV['KARAFKA_ENV'] = ENV['RAILS_ENV']
require ::File.expand_path('../config/environment', __FILE__)

return unless Rails.application

Rails.application.eager_load!
```
