### ISSUE TITLE
Error handling in Karafka?

### ISSUE THREAD

**Issue by ariieh** [karafka/karafka#309]
Been running in production with Karafka for a few weeks now and just ran into a potentially big issue I wasn't aware of -- it seems there's no error handling in Karafka, a la Sidekiq. Any exception raised in any consumer takes down the whole server. Is this something being worked on? Definitely a blocker to us from using this at a larger scale.

**Comment by mensfeld** [comment]
Could you elaborate more on that? What type of error? Can it be reproduced? What do you mean by "takes down"? More details please.

**Comment by mensfeld** [comment]
up until I get more details, marked as invalid as I don't have enough information to comment

**Comment by mensfeld** [comment]
Also, before answering me, please refer to this: https://github.com/karafka/karafka/blob/master/lib/karafka/connection/listener.rb#L28

**Comment by ariieh** [comment]
@mensfeld Sorry, I could have been more clear. I accidentally deployed some broken code to production (`NameError` from an undefined local variable), in one Karafka consumer, and it seemingly crashed the whole Karafka server. The server would not boot until I fixed the bug. Perhaps I'm misunderstanding or did something wrong, but I interpreted this to mean that Karafka has no exception handling.

I do see the linked exception handling code though -- I read this as Karafka will shut down a given topic consumption, _and only that topic consumption_, if there's an exception raised in the topic consumer. It's not supposed to shut down the server. Is this correct? I also don't understand this comment: `Business logic problems should not propagate this far`. Is there some other exception handling code I'm missing?

Anyway, rereading the post my tone comes off as a little snarky, definitely did not intend that -- if there's an issue here we're definitely willing to do the work to fix it!

**Comment by mensfeld** [comment]
>  Sorry, I could have been more clear. I accidentally deployed some broken code to production (NameError from an undefined local variable), in one Karafka consumer, and it seemingly crashed the whole Karafka server.

Could you prepare a test case?

>  The server would not boot until I fixed the bug

Obviously. If the code was executed during the boot - it is the only expected behavior. Try doing something bad in puma.rb and start it ;) - won't happen

>  I read this as Karafka will shut down a given topic consumption, and only that topic consumption
It will shutdown BUT will attempt to recover first.

>  It's not supposed to shut down the server. Is this correct?
If the server started properly, nothing should be able to stop it ;) (as long as there are threads with consumers ofc)

> Is there some other exception handling code I'm missing?

Yes:

- https://github.com/karafka/karafka/blob/master/lib/karafka/connection/listener.rb#L46
- https://github.com/karafka/karafka/blob/master/lib/karafka/connection/client.rb#L34
- https://github.com/karafka/karafka/blob/master/lib/karafka/connection/client.rb#L46
- https://github.com/karafka/karafka/blob/master/lib/karafka/fetcher.rb#L28

All of those are designed to protect the server from shutting down as long as it was started properly. No user logic errors should affect Karafka. If a user error occurs for a given topics partition, the processing for this topics partitions messages will stop and Karafka will retry after a while.

**Comment by ariieh** [comment]
"Obviously. If the code was executed during the boot - it is the only expected behavior. Try doing something bad in puma.rb and start it ;) - won't happen"

This wasn't an error during boot, though -- it was an error in the `consume` method of an individual consumer. Anyway, I can't seem to replicate it locally (getting the retry stuff etc.), but if I can definitely will introduce a test case. We can close this for now.

**Comment by mensfeld** [comment]
If you are able to reproduce - I will be happy to fix that :) thank you for fast answer. Up until we're able to reproduce, I will keep it marked as invalid. Please reopen if the problem persists.

**Comment by mensfeld** [comment]
Just as a reference: https://github.com/karafka/karafka/issues/311

**Comment by mensfeld** [comment]
@ariieh is this description sufficient enough based on your previous experience with Karafka? https://github.com/karafka/karafka/wiki/Error-handling-and-back-off-policy
