### ISSUE TITLE
Single consumer can support only one topic

### ISSUE THREAD

**Issue by imanel** [karafka/karafka#369]
Currently consumer is saving topic name as class variable, so if it will get used several times for different topic only last one will get stored and exposed via `topic` variable. It would be useful to either allow for multiple topics per controller (so set this variable for each instance of consumer) or raise error when trying to reuse the same consumer in multiple topics.

**Comment by mensfeld** [comment]
True is that. Targeted to 1.3. Will investigate soon (once the cache for inflections on one of the open PRs is done). Thank you.

**Comment by mensfeld** [comment]
Since the consumer class in enriched with some functionalities depending on the context for which it runs, we cannot really do that per instance (performance wise and due to the fact that it would seriously impact the global method cache). I will add certain validations to the routing rules to ensure it is detected and reported.

**Comment by mensfeld** [comment]
actually this wouldn't be a problem if we would drop the `persistent` `false` (that is not the default) at all. That way we could pre build during startup all the needed options and allow the instances to run independently within their execution context. Thanks!

**Comment by mensfeld** [comment]
ref: https://github.com/karafka/karafka/issues/377

**Comment by mensfeld** [comment]
@imanel feel free to check again 1.3-wip if you want.
