### ISSUE TITLE
Remove singleton and class level global references

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#370]
If we're going to support guilds and provide possibility to operate multiple instances of karafka apps (with optional subsets of topics, etc), we need to remove global references.

**Comment by mensfeld** [comment]
part 1: topics aren't anyhow class level limited

**Comment by mensfeld** [comment]
I'm not assigning any milestones as it is an ongoing process.

**Comment by ka8725** [comment]
I almost completed the write the issue https://github.com/karafka/karafka/issues/546 and only then noticed there is already issue for that, this one. But since it has some more explanation I decided to submit it eventually. So it's a duplicate now, but feel free to drop it if you see no reason in it. Thanks!

**Comment by mensfeld** [comment]
@ka8725 thanks! :) I will reply to you there

**Comment by mensfeld** [comment]
I'm closing this one as it is slowly happening. Not sure if all the things are going to be fixed in 2.0 but many already are.
