### ISSUE TITLE
Karafka server raises error if database connection is terminated.

### ISSUE THREAD

**Issue by shifakhan** [karafka/karafka#381]
While running karafka server for a rails app, if the database connection is terminated, the rails server is able to reconnect with the database, however, karafka server is unable to do so, and any subsequent calls to database fail with the error
`PG::ConnectionBad: PQsocket() can't get socket descriptor`
Shouldn't the database connection be re-established in case it disconnects? What would be the recommend way to check if the database connection is still active, and there'll be no connection errors while running Karafka controller code?

Rails version - 5.0.6
Karafka gem version - 1.1.0
PostgreSQL version - 9.6
[PG gem](https://github.com/ged/ruby-pg) version - 0.21.0

Steps to reproduce: 
- Create a new rails app, with a postgres database with name say `test_db`. 
- Start rails server on default port 3000
- Create a new consumer, topic, and its controller. In the controller, make a call to Database to save message in a table.
- Send a message to the topic from a producer. (Controller should be successfully able to save received kafka message to database)
- Run `SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'test_db';`. This will kill all client connections to that database. 
- When you run `SELECT pid,application_name FROM pg_stat_activity WHERE datname = 'test_db' ;`, you would not see `rails` or `karafka` in the application name. 
- When you go to localhost:3000 in your browser, and run the above query again, rails reappears hence the rails app is connected to DB again. When you send another message from the producer, the message is consumed, but app throws error when message is saved to database.

**Comment by mensfeld** [comment]
This indeed sounds like a bug. I will investigate it tomorrow morning. @nijikon you can give it a shot as well. AR shouldn't anyhow leak out nor karafka should.

**Comment by mensfeld** [comment]
@shifakhan did you try reproducing using karafka 1.2?

**Comment by shifakhan** [comment]
@mensfeld I haven't. I can look into it though. Do you think there might be changes related to the problem in the version change?

**Comment by mensfeld** [comment]
@shifakhan I have no idea for now but I'm almost there with the reproduction.

**Comment by mensfeld** [comment]
@shifakhan this requires a bigger investigation but a quick patch would be to wrap the `#consume` like that:

```ruby
  def consume
    Example.create!(params_batch.first['example'].except('id'))
  rescue ActiveRecord::StatementInvalid
    ::ActiveRecord::Base.clear_active_connections!
    retry
  end
```

this will force PG to reconnect.

**Comment by mensfeld** [comment]
This is exactly how Sidekiq does it - they clear the connections and retry the task, but nonetheless the exception is being raised.

**Comment by shifakhan** [comment]
Thanks a bunch @mensfeld ! This indeed fixes the issue. 🙇‍♀️

**Comment by mensfeld** [comment]
@shifakhan it's not a bug tbh. I will give you a complex (and long) explanation in max 1 day. I will also add it to FAQ and readme.

**Comment by mensfeld** [comment]
Ok, so I think I have a spare 10 minutes to write a more complex answer. Let me start with the fact, that it is indeed a **feature**.  And I will try to explain why and if I''m successful, @shifakhan please close this issue and I will make this part of our official docs.

### Why Karafka does not restart dead PG connections?

While running `karafka server` with a Rails application that uses ActiveRecord, if the database connection is terminated, the Rails HTTP server is able to reconnect with the database, however, Karafka server is unable to do so. Any subsequent calls to database fail with the following error:

```
PG::ConnectionBad: PQsocket() can't get socket descriptor
```

Related sub-questions:

-  Shouldn't the database connection be re-established in case it disconnects?
- What would be the recommended way to check if the database connection is still active?

#### Short answer

This is an expected behavior because it is meant to be transaction supporting system with long living consumers.

#### Long answer

By default, Karafka consumers **are** persistent. It means, that multiple messages / message batches from the same topic and partition will be processed by **the same** consumer instance.

Thanks to that approach, it is super easy to implement flushing engines and support in memory computation and transactions (for example when listening to a topic with user state changes), without actually hitting the DB. There may be a case where you want to start a transaction and run it across several received batches and only close it (COMMIT) once everything is done. If Karafka would handle the reconnection on its own, there would be a chance that data is not being wrapped within a transaction, as it would have ended with the disconnected connection. In a case like that, the code would keep running with an assumption that there's an active transaction. This could have a critical impact on some of the systems that rely heavily on SQL transactions.

But you may ask: **why Puma is restarting the connections?** Truth be told it is doing exactly the same thing as Karafka, just the operation scope is different. For Puma, we don't spin up a single cross-request transactions as HTTP requests by definition should be stateless. This means that we can easily "recover" from a disconnection event for a brand new request. Exactly the same happens within Sidekiq. Due to the fact, that it encourages you to use **reentrancy**, it will fail for the current job and within the new scope (after retry) it will reconnect. But the reconnection will take care of a new job (despite the fact that it is restarted - it is still new).

### How can I make Karafka restart dead PG connections?

You can easily catch the ```ActiveRecord::StatementInvalid``` error and decide on your own how to handle a dead connection. If you do atomic (per received batch) operations, you can just catch this and run the `::ActiveRecord::Base.clear_active_connections!` method:

```ruby
# We work with an assumption that you process messages one by one here
def consume
 Example.create!(params['example'])
rescue ActiveRecord::StatementInvalid
  ::ActiveRecord::Base.clear_active_connections!
  retry
end
```

Depending on your approach towards building robust applications and providing reusable code, you may:

a) separate this from your business logic and leave it with a retry on the abstract Karafka layer as long as you understand what you are doing;
b) make it part of your business logic (wouldn't recommend).

For the solution **a)** you can easily extend Karafkas ``ApplicationConsumer#call`` method as followed:

```ruby
# frozen_string_literal: true

class ApplicationConsumer < Karafka::BaseConsumer
  def call
    super
  rescue ActiveRecord::StatementInvalid => e
    BugTracker.notify(e)
    ::ActiveRecord::Base.clear_active_connections!
    # You probably want to implement a counter and a custom error not to
    # end up with an endless loop
    retry
  end
end
```

That way, you don't have to worry about the retries within your business logic, but please be aware of the fact, that you will have to design your software to support **reentrancy** especially if you're batch processing within a `#consume` operation.

If you decide to go with the solution **b)**, here's how you can implement it:

```ruby
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  class << self
    def with_disconnection_retry
      yield
    rescue ActiveRecord::StatementInvalid
      ::ActiveRecord::Base.clear_active_connections!
      # You probably want to implement a counter and a custom error not to
      # end up with an endless loop
      retry
    end
  end
end
```

Now you can just use it for anything you need like so:

```ruby
def consume
  ApplicationRecord.with_disconnection_retry do
    Example.create!(params['example'])
  end
end
```

**Comment by nijikon** [comment]
Very nice explanation @mensfeld. If it's clear to @shifakhan, we definitely should add it to the docs.

**Comment by shifakhan** [comment]
Thanks for the detailed explanation @mensfeld ! The behaviour definitely makes sense now.

**Comment by mensfeld** [comment]
@shifakhan any time. I've made a separate page describing that issue: https://github.com/karafka/karafka/wiki/Problems-and-Troubleshooting :)
