### ISSUE TITLE
Karafka consumer isolation

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#570]
> I did not look deep into karafka source code but looks like karafka leverages process isolation for consumer isolation.
> 
> Is the consumer_group tightly coupled to the process or the consumer class itself?
> 
> The costs associated with spawning a separate JVM per consumer group may not be scalable for JRuby and might be better to run multiple threads in the JVM. It might add the possibility of running multiple consumers in different consumer groups within the same process where using a single consumer to subscribe to multiple topics is not feasible.
> 
> I'm confident that this approach may not fit in libraries like karafka itself where majority of users run MRI Ruby. I just want to hear your thoughts on the approach.

ref from @Adithya-copart: https://github.com/appsignal/rdkafka-ruby/pull/106

**Comment by mensfeld** [comment]
@Adithya-copart what do you mean by:

> Is the consumer_group tightly coupled to the process or the consumer class itself?

Karafka can run with several threads in parallel now. There has been a discussion about that here: https://github.com/karafka/karafka/issues/481 please refer to my extensive answer.

Karafka 2.0 will fully elevate multi threading for any Ruby implementation.

**Comment by Adithya-copart** [comment]
Thanks for opening the issue @mensfeld. I will look into the extensive documentation.

To put context into that question, I'm coming from `racecar` where one consumer is run in a process. Adding a new consumer to the same group requires a separate process.

Looking at your answer in https://github.com/karafka/karafka/issues/481, we can run multiple consumers in `karafka` and they could be in different consumer groups which answers my question.

Out-of-context: Installing `karafka` `master` in JRuby does not work at the moment and should be fixed with https://github.com/ruby/io-console/issues/10

**Comment by mensfeld** [comment]
@Adithya-copart FYI karafka 2.0 now is fully multi-threaded: https://mensfeld.pl/2022/08/karafka-framework-2-0-announcement/
