### ISSUE TITLE
Why do I need to require the boot file from config/environment.rb

### ISSUE THREAD

**Issue by olegzaporozhchenko** [karafka/karafka#645]
Hello. First of all thanks for your great work.

Could you please clarify a few things about the Rails integration for me?

The original documentation suggest to add the `require Rails.root.join(Karafka.boot_file)` code to the END of `config/environment.rb` file. However, I didn't find any reason to do this besides making tests work. Maybe it could be useful for the WaterDrop?

As the result, this line will just validate the Karafka config and nothing else, but I would like to avoid it for two reasons:

1. It will require to add all the karafka ENV variables for the Rails server pods
2. It will add a confusing message that looks like karafka was run within the webserver process. But it's not

Did I miss something? https://github.com/maelfosso/authentication-kafka/pull/1/files Here you are pointing that I need it for class loading but it works as well without this code. Any other reasons to make this? Because it looks like the cycled requires: karafka.rb requires the config/environment.rb which requires the karafka.rb

**Comment by mensfeld** [comment]
Hello @olegzaporozhchenko. Thank you for taking interest in the Karafka ecosystem.

Indeed if you do not plan to use WaterDrop or you do not plan to reference any of the dynamically built Karafka objects (like workers for Sidekiq plugin or consumers) you do not have to do this.

The configuration in the readme is the "default" that aims to suit the majority of the users, that's why it's recommended by default, so everything works out of the box.
