### ISSUE TITLE
Backoff configuration

### ISSUE THREAD

**Issue by Geokoumpa** [karafka/karafka#67]
Hello, 

after an incident that our Kafka producer generated a huge backlog, Karafka Sidekiq used huge ammounts of Ram while queueing everything in Redis. So the question is, is there a way to set a backoff configuration, so that the consumer stops fetching messages if the Sidekiq queue is maxed out?

Best
Giorgos

**Comment by mensfeld** [comment]
@Geokoumpa hello - this sounds like a feature request - feel free to provide it (or if you cannot  - give us some time and we will implement this).

**Comment by Geokoumpa** [comment]
Hey, thanks for the quick response. Can you provide me with some guidance, how would I achieve this kind of control? I can attempt to do it. Thanks

**Comment by mensfeld** [comment]
@Geokoumpa  you're welcome.

First of all there's a [config](https://github.com/karafka/karafka/blob/master/lib/karafka/config.rb) class that will require this setting to be defined . I think this could be defined as a lambda object that would have to return false. Something like ((just remember to handle a nil case):
```
  setup do |config|
    # Other setup stuff...
    config.backoff_policy = -> { Karafka::Connection::Backoff.new(|route| RedisQueueSizeChecker.new.enough_resources_for?(route.topic), timeout: 5) }
  end
```

Would be awesome if it could yield route on which it will listen - then framework users could prioritize backoff based not only on the condition but also the route parameters (topic, etc).

I believe in SRP as much as it can be used, that's why I vote or creating a new object in Connection namespace ( @agwozdowski  / @pavlo-vavruk  what do you think about that?) like Connection::BackOff (you can propose different naming - this is just an example) that would prevent from fetching messages. This can be implemented in the [actor cluster](https://github.com/karafka/karafka/blob/master/lib/karafka/connection/actor_cluster.rb) since this is the place where we initialize listeners and fetch data. If the backoff policy would be applied (and we backoff) the:
```
listener.fetch(block)
```
would be never excuted.

Last problem there is is the wait time until recheck. Without it (and with backoff policy on) it would constantly run the lambda defined (idea - lambda could return a policy object with both - status and wait time that could default).

If you have any questions - feel free to ask and thank you for the contribution!

**Comment by mensfeld** [comment]
Btw from curiosity - could you provide us with some numbers and details on how do you use Karafka? :)

**Comment by Geokoumpa** [comment]
Yes, we use Karafka as one of the last links in our stream processing chain. The first link is Logstash, where we capture network device logs and produce kafka messages. Then some processing takes place in Storm, and the output is fed into Karafka.

This means that if Storm fails permanently, backlog is generated and when Storm is back up, we have the Ram issue I described earlier.

We process 80 - 90 million messages daily.

We would be very happy to replace Storm with Karafka, so this is considered very important to us.

I will try to get familiar  with the codebase of Karafka and see if I can be of any help, other than that any progress on this feature is highly appreciated :)

**Comment by mensfeld** [comment]
@Geokoumpa first of all, I'm really glad that you find Karafka useful :)

If you decide that you're not able to do that without my help - I can implement that next week. It should not take me longer than few h. The only thing that is unknown now is the naming ;)

**Comment by Geokoumpa** [comment]
I'd be glad to do this, my only concern is I don't think I will be able to come up with the same level of abstraction as the one you just described. In the end, what is a matter of a few hours for you, could take a few days for me :D For starters, I will make sure I try to understand the ins and outs of Karafka.

Best
Giorgos

**Comment by mensfeld** [comment]
@Geokoumpa yes of course. I will help you with that more if you join us on gitter :)

**Comment by mensfeld** [comment]
@Geokoumpa did you work on that already or is it ok to take it and implement?

**Comment by Geokoumpa** [comment]
Sadly, although we still use karafka in production, I didn't have the time to get busy with this feature.

**Comment by mensfeld** [comment]
@Geokoumpa  no worries - one more feature that I need in Karafka and I will do implement this one as well ;)

**Comment by mensfeld** [comment]
I will close that now. You can implement this using before_enqueue feature per controller.
