### ISSUE TITLE
ActiveJob queue name changes not reflected in routes consumer

### ISSUE THREAD

**Issue by whithajess** [karafka/karafka#798]
ActiveJob queue name changes not reflected in routes consumer

## Expected behavior

When setting a different prefix and delimiter for active_job (standard active_job options)

```ruby
    config.active_job.queue_name_prefix = 'com.default'
    config.active_job.queue_name_delimiter = '.'
```

I would expect that then using:
```
queue_as :job
```

I would publish and read from the topic  `com.default.job` in Karafka

## Actual behaviour

The publish to Kafka is done to `com.default.job` but when using:

```ruby
  routes.draw do
    active_job_topic :job
  end
```

Its looking for just `job` as the topic rather than `com.default.job`

Can get this to work by being explicit:
```ruby
  routes.draw do
    active_job_topic 'com.default.job'
  end
```

## Steps to reproduce the problem

As above.

## Your setup details

```
Karafka version: 2.0.0.alpha2
Ruby version: 3.1.0
Rdkafka version: 0.11.1
Subscription groups count: 1
Workers count: 1
Application client id: default-job
Boot file: karafka.rb
Environment: development
License: LGPL-3.0
```

**Comment by whithajess** [comment]
Another workaround (untested) potentially in: https://github.com/karafka/karafka/wiki/Consumer-and-topic-mappers#topic-mappers

I still feel like this should work out of the box however.

**Comment by mensfeld** [comment]
Fair point. Let me think about it and get back to you

**Comment by mensfeld** [comment]
Ok so my suggestion based on my quick POC would be to change the interface for this as followed:

is:
```ruby
active_job_topic :job
```

could be:

```ruby
active_job_topic JobName
```

then under the hood I could fetch the queue name from the job class by running `job_class.new.queue_name`:

it would work as you want without any changes if you would:

```ruby
active_job_topic JobClass.new.queue_name
```

WDYT?

**Comment by whithajess** [comment]
Hmm I guess the only downside to that approach would be that actual job_class isn't necessarily tied to the queue_name - often something like a `default` queue could be used by multiple Jobs.

**Comment by mensfeld** [comment]
@whithajess fair point. Let me dive deep into the AJ API to see if there is a way to construct the name without building a job processor.

**Comment by mensfeld** [comment]
Ok. As I thought: aside from global (per app) config, each job can have its own customizable config that ends up modifying the queue name.

There are three ideas I have on that and none of them is great:

- Use the syntax above and remove duplicates: that way when you define the same queue several times, it is still going to work
- Load all active jobs and use descendants tracking to iterate over them, fetch queues and use this data to define topics - would require eager load and potentially would break stuff. 
- Leave it as it is and just document that you can either define topics manually or reference it via something like this:

```ruby
topics = [
  Job1, Job2, Job3
].map(&:new).map(&:queue_name).uniq

topics.each {  active_job_topic _1 }
```

I would opt on the last one because the dependence of Karafka on AJ specific magic would not be tight and the docs can be pretty good about that.

**Comment by mensfeld** [comment]
Hey @whithajess I decided to leave it as it is. I will do my best to document this in the ActiveJob docs section.

ref https://github.com/karafka/wiki/issues/8

Any other solution will either be really problematic to maintain or problematic to use due to tight coupling with Rails. 

Feel free to reopen / comment if you have alternative ideas around it.

**Comment by whithajess** [comment]
Hey @mensfeld apologies about my delay on getting back to you on this.

I have had a look at some of the other main ActiveJob queue adapters around how they handle this.

**Backburner**

Duplicated config available to match the ActiveJob configs

```
tube_namespace | Prefix used for all tubes related to this backburner queue.
namespace_separator | Separator used for namespace and queue name
```
**Delayed Job**

No solution - Issue lodged: https://github.com/collectiveidea/delayed_job/issues/1095

**Resque**

Takes advantage of [redis namespaces]( https://github.com/resque/resque#namespaces) no solution for delimiters I could see.

**Sidekiq**

Suggests never to do so and instead use multiple redis databases as its more in tune with the backend service

<hr>

From what you have suggested and looking at the alternative implementations I wonder if what `Backburner` did and just create a matching config settable in `Karafka` may be better than just documenting how to do it manually?

**Comment by mensfeld** [comment]
I reopened it to have it open until we reach a conclusion.

Backburner indeed uses duplicated config settings but as far as I can see it has them only on a global level.

ActiveJob allows you to redefine those per job as well with different values:

```ruby
Rails.configuration.active_job.queue_name_prefix #=> nil
VisitorsJob.queue_name_prefix #=> nil
VisitorsJob.queue_name_prefix = 'test'
Rails.configuration.active_job.queue_name_prefix #=> nil
VisitorsJob.new.queue_name #=> 'test_default'
```

This means, that effectively one setting would not cover all the cases but just one of them.

This in my opinion would be even worse than not supporting it at all, as would introduce an edge cases.

The more I think about it, the more I do not want to do this beyond adding extensive docs and examples.

To make it work with any case it would have to be detected based on jobs classes, which in the end would mean me fighting with zeitwerk and rails to load it in a decent fashion while still having the autoload instead of forcing eager load how it is done in 1.4.

The only other viable option that would "I think always work" is to listing all the jobs in the karafka router but that pretty much equals the above.

Karafka 1.4 has two "magic mapping" concepts and I consider both of them bad ideas:

- consumer mappers
- topic mappers

The number of issues related to them, support requests and questions is big. The "magic mappings" while used by some in an extremely smart way introduce non-explicit edge cases and cause confusion.

topic mappers are retired in 2.0 and I will probably retire consumer mappers in 3.0 (yeah, thinking ahead ;) ).

I can make explicit docs as well as inline docs for the rails auto generated template + examples test coverage in the integrartions  to tackle those.

**Comment by whithajess** [comment]
Thanks for looking into this again.

I didn't realise that ActiveJob also allowed per job queue prefix - I completely agree with your assessment that in this instance adding a global config that only handles some of the cases is not a good choice.

Agree documentation is probably the best way forward in this instance.
