### ISSUE TITLE
2.0: Do not fail without install

### ISSUE THREAD

**Issue by bragovo** [karafka/karafka#817]
If just add gem to Gemfile and do not run install command app must working as before.

--------

## Expected behavior

Server, console, spec, etc.. fails if karafka.rb does not exists (https://github.com/karafka/karafka/blob/2.0/lib/karafka/railtie.rb#L21)

## Actual behavior

App continue works as before karafka gem was added.

## Steps to reproduce the problem

Add to Gemfile:
```
gem "karafka", "~> 2.0.0.alpha5"

# or

spec.add_dependency "karafka", "~> 2.0.0.alpha5"
```
And do not run install or create manually karafka.rb

Run anything
```
bundle exec rails s
bundle exec rails c
bundle exec rspec
```

<img width="813" alt="image" src="https://user-images.githubusercontent.com/822911/162006599-dac61d48-46d2-4231-ad69-6f1ecdc3b05f.png">

**Comment by mensfeld** [comment]
My suggestion for a fix here:

if `KARAFKA_BOOT_FILE` will be set to false it will not be used. Is that ok? Karafka by default is not meant to be a second class citizen and I don't want to silently hide the missing boot file because it will cause a lot of problems for other ppl but `KARAFKA_BOOT_FILE=false` would be something I am willing to add.

**Comment by bragovo** [comment]
Sure, I think it's perfect 👍

**Comment by mensfeld** [comment]
@bragovo here you go: https://github.com/karafka/karafka/pull/824
