### ISSUE TITLE
Karafka server - possiblity to run it only for a certain consumer groups

### ISSUE THREAD

**Issue by mensfeld** [karafka/karafka#96]
Similarly to how it is done in Sidekiq:

q, --queue QUEUE[,WEIGHT]       Queues to process with optional weights

**Comment by mensfeld** [comment]
@mach-kernel  any idea on the DSL for that? Should we build up some sort of orchestration or just add an CLI option and leave the rest to the users (I would prefer the second one)?

**Comment by mach-kernel** [comment]
We could add an `--only-topics=c,s,v` kind of flag for bare min functionality. I think that anything more would probably involve making DSL for it, but I don't really know how to represent that parity since I think each Karafka server process would then at minimum need to be aware of what topics its peers are subscribed to and that kind of sync seems to be an exercise we don't need to do at the current time. 

Agree?

**Comment by mensfeld** [comment]
@mach-kernel that is good. I've figured out a way to do it easily I think and I should be able to make it for 0.6 :)
